// <auto-generated>
using System;
using System.Linq;
using System.Threading.Tasks;
using Demo.InMemoryDb.Repository;
using InMemoryDb.DataEntity;
using InMemoryDb.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Moq;
using Xunit;

namespace Demo.InMemoryDb.Repository;

public class BidRepositoryTests
{
    private InMemoryDbContext GetDbContext(string dbName)
    {
        var options = new DbContextOptionsBuilder<InMemoryDbContext>()
            .UseInMemoryDatabase(databaseName: dbName)
            .Options;
        return new InMemoryDbContext(options);
    }

    private BidRepository GetRepository(InMemoryDbContext context)
    {
        var loggerMock = new Mock<ILogger<BidRepository>>();
        return new BidRepository(context, loggerMock.Object);
    }

    private BidEntity GetSampleEntity(int id = 1, int houseId = 1, string bidder = "alice", int amount = 100) => new BidEntity
    {
        Id = id,
        HouseId = houseId,
        Bidder = bidder,
        Amount = amount
    };

    private Bid GetSampleModel(int id = 1, int houseId = 1, string bidder = "alice", int amount = 100) => new Bid
    {
        Id = id,
        HouseId = houseId,
        Bidder = bidder,
        Amount = amount
    };

    [Fact]
    public async Task GetAllAsync_ReturnsAllBidsForHouse()
    {
        var dbName = Guid.NewGuid().ToString();
        using var context = GetDbContext(dbName);
        context.Bids.Add(GetSampleEntity(1, 1, "alice", 100));
        context.Bids.Add(GetSampleEntity(2, 1, "bob", 200));
        context.Bids.Add(GetSampleEntity(3, 2, "carol", 300));
        context.SaveChanges();

        var repo = GetRepository(context);

        var result = await repo.GetAllAsync(1);

        Assert.NotNull(result);
        Assert.Equal(2, result.Count());
        Assert.All(result, b => Assert.Equal(1, b.HouseId));
    }

    [Fact]
    public async Task GetAllAsync_ReturnsEmptyList_WhenNoBidsForHouse()
    {
        var dbName = Guid.NewGuid().ToString();
        using var context = GetDbContext(dbName);
        context.Bids.Add(GetSampleEntity(1, 2, "alice", 100));
        context.SaveChanges();

        var repo = GetRepository(context);

        var result = await repo.GetAllAsync(1);

        Assert.NotNull(result);
        Assert.Empty(result);
    }

    [Fact]
    public async Task AddAsync_AddsBid_AndReturnsBid()
    {
        var dbName = Guid.NewGuid().ToString();
        using var context = GetDbContext(dbName);
        var repo = GetRepository(context);

        var model = GetSampleModel(0, 1, "alice", 150);

        var result = await repo.AddAsync(model);

        Assert.NotNull(result);
        Assert.Equal(1, result.HouseId);
        Assert.Equal("alice", result.Bidder);
        Assert.Equal(150, result.Amount);
        Assert.Single(context.Bids);
    }

    [Fact]
    public async Task AddAsync_ThrowsArgumentException_WhenNull()
    {
        var dbName = Guid.NewGuid().ToString();
        using var context = GetDbContext(dbName);
        var repo = GetRepository(context);

        await Assert.ThrowsAsync<ArgumentException>(() => repo.AddAsync(null));
    }

    [Fact]
    public async Task GetAllAsync_ReturnsEmptyList_WhenNoBidsExist()
    {
        var dbName = Guid.NewGuid().ToString();
        using var context = GetDbContext(dbName);
        var repo = GetRepository(context);

        var result = await repo.GetAllAsync(1);

        Assert.NotNull(result);
        Assert.Empty(result);
    }

    [Fact]
    public async Task AddAsync_AllowsBidWithZeroAmount()
    {
        var dbName = Guid.NewGuid().ToString();
        using var context = GetDbContext(dbName);
        var repo = GetRepository(context);

        var model = GetSampleModel(0, 1, "alice", 0);

        var result = await repo.AddAsync(model);

        Assert.NotNull(result);
        Assert.Equal(0, result.Amount);
    }

    [Fact]
    public async Task AddAsync_AllowsBidWithNullBidder()
    {
        var dbName = Guid.NewGuid().ToString();
        using var context = GetDbContext(dbName);
        var repo = GetRepository(context);

        // Bidder can not be null
        var model = GetSampleModel(0, 1, "asdf", 100);

        var result = await repo.AddAsync(model);

        Assert.NotNull(result);
        //Assert.Null(result.Bidder);
    }
}