// <auto-generated>
using System;
using System.Linq;
using System.Threading.Tasks;
using Demo.InMemoryDb.Repository;
using InMemoryDb.DataEntity;
using InMemoryDb.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Moq;
using Xunit;

namespace Demo.InMemoryDb.Repository;

public class HouseRepositoryTests
{
    private InMemoryDbContext GetDbContext(string dbName)
    {
        var options = new DbContextOptionsBuilder<InMemoryDbContext>()
            .UseInMemoryDatabase(databaseName: dbName)
            .Options;
        return new InMemoryDbContext(options);
    }

    private HouseRepository GetRepository(InMemoryDbContext context)
    {
        var loggerMock = new Mock<ILogger<HouseRepository>>();
        return new HouseRepository(context, loggerMock.Object);
    }

    private HouseEntity GetSampleEntity(int id = 1) => new HouseEntity
    {
        Id = id,
        Address = "123 Main St",
        Country = "USA",
        Description = "A nice house",
        Price = 100000,
        Photo = "photo.jpg",
        RowVersion = new byte[] { 1, 2, 3 }
    };

    private House GetSampleModel(int id = 1) => new House
    {
        Id = id,
        Address = "123 Main St",
        Country = "USA",
        Description = "A nice house",
        Price = 100000,
        Photo = "photo.jpg",
        RowVersion = new byte[] { 1, 2, 3 }
    };

    [Fact]
    public async Task GetAllAsync_ReturnsAllHouses()
    {
        var dbName = Guid.NewGuid().ToString();
        using var context = GetDbContext(dbName);
        context.Houses.Add(GetSampleEntity(1));
        context.Houses.Add(GetSampleEntity(2));
        context.SaveChanges();

        var repo = GetRepository(context);

        var result = await repo.GetAllAsync();

        Assert.NotNull(result);
        Assert.Equal(2, result.Count());
    }

    [Fact]
    public async Task GetAllAsync_ReturnsEmptyList_WhenNoHouses()
    {
        var dbName = Guid.NewGuid().ToString();
        using var context = GetDbContext(dbName);
        var repo = GetRepository(context);

        var result = await repo.GetAllAsync();

        Assert.NotNull(result);
        Assert.Empty(result);
    }

    [Fact]
    public async Task GetAsync_ReturnsHouse_WhenExists()
    {
        var dbName = Guid.NewGuid().ToString();
        using var context = GetDbContext(dbName);
        context.Houses.Add(GetSampleEntity(1));
        context.SaveChanges();

        var repo = GetRepository(context);

        var result = await repo.GetAsync(1);

        Assert.NotNull(result);
        Assert.Equal(1, result.Id);
    }

    [Fact]
    public async Task GetAsync_ReturnsNull_WhenNotFound()
    {
        var dbName = Guid.NewGuid().ToString();
        using var context = GetDbContext(dbName);
        var repo = GetRepository(context);

        var result = await repo.GetAsync(99);

        Assert.Null(result);
    }

    [Fact]
    public async Task AddAsync_AddsHouse_AndReturnsHouse()
    {
        var dbName = Guid.NewGuid().ToString();
        using var context = GetDbContext(dbName);
        var repo = GetRepository(context);

        var model = GetSampleModel(1);

        var result = await repo.AddAsync(model);

        Assert.NotNull(result);
        Assert.Equal(model.Address, result.Address);
        Assert.Single(context.Houses);
    }

    [Fact]
    public async Task AddAsync_ThrowsArgumentException_WhenNull()
    {
        var dbName = Guid.NewGuid().ToString();
        using var context = GetDbContext(dbName);
        var repo = GetRepository(context);

        await Assert.ThrowsAsync<ArgumentException>(() => repo.AddAsync(null));
    }

    [Fact]
    public async Task UpdateAsync_UpdatesHouse_AndReturnsHouse()
    {
        var dbName = Guid.NewGuid().ToString();
        using var context = GetDbContext(dbName);
        context.Houses.Add(GetSampleEntity(1));
        context.SaveChanges();

        var repo = GetRepository(context);

        var updated = GetSampleModel(1) with { Address = "456 Elm St" };
        //updated.Address = "456 Elm St";

        var result = await repo.UpdateAsync(updated);

        Assert.NotNull(result);
        Assert.Equal("456 Elm St", result.Address);
        Assert.Equal("456 Elm St", context.Houses.First().Address);
    }

    [Fact]
    public async Task UpdateAsync_ThrowsArgumentException_WhenNotFound()
    {
        var dbName = Guid.NewGuid().ToString();
        using var context = GetDbContext(dbName);
        var repo = GetRepository(context);

        var model = GetSampleModel(99);

        await Assert.ThrowsAsync<ArgumentException>(() => repo.UpdateAsync(model));
    }

    [Fact]
    public async Task DeleteAsync_DeletesHouse_AndReturnsTrue()
    {
        var dbName = Guid.NewGuid().ToString();
        using var context = GetDbContext(dbName);
        context.Houses.Add(GetSampleEntity(1));
        context.SaveChanges();

        var repo = GetRepository(context);

        var result = await repo.DeleteAsync(1);

        Assert.True(result);
        Assert.Empty(context.Houses);
    }

    [Fact]
    public async Task DeleteAsync_ThrowsArgumentException_WhenNotFound()
    {
        var dbName = Guid.NewGuid().ToString();
        using var context = GetDbContext(dbName);
        var repo = GetRepository(context);

        await Assert.ThrowsAsync<ArgumentException>(() => repo.DeleteAsync(99));
    }

    // Edge case: AddAsync with minimal data
    [Fact]
    public async Task AddAsync_AllowsHouseWithNullProperties()
    {
        var dbName = Guid.NewGuid().ToString();
        using var context = GetDbContext(dbName);
        var repo = GetRepository(context);

        var model = new House { Id = 2 };

        var result = await repo.AddAsync(model);

        Assert.NotNull(result);
        Assert.Equal(2, result.Id);
    }

    // Edge case: UpdateAsync with null/empty fields
    [Fact]
    public async Task UpdateAsync_UpdatesHouse_WithNullFields()
    {
        var dbName = Guid.NewGuid().ToString();
        using var context = GetDbContext(dbName);
        var entity = GetSampleEntity(3);
        context.Houses.Add(entity);
        context.SaveChanges();

        var repo = GetRepository(context);

        var updated = new House
        {
            Id = 3,
            Address = null,
            Country = null,
            Description = null,
            Price = 0,
            Photo = null,
            RowVersion = null
        };

        var result = await repo.UpdateAsync(updated);

        Assert.NotNull(result);
        Assert.Null(result.Address);
        Assert.Null(result.Country);
    }
}