// <auto-generated>
using System;
using System.Linq;
using System.Threading.Tasks;
using Demo.InMemoryDb.Repository;
using InMemoryDb.DataEntity;
using InMemoryDb.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Moq;
using Xunit;

namespace Demo.InMemoryDb.Repository;

public class SpeakerRepositoryEdgeCaseTests
{
    private InMemoryDbContext GetDbContext(string dbName)
    {
        var options = new DbContextOptionsBuilder<InMemoryDbContext>()
            .UseInMemoryDatabase(databaseName: dbName)
            .Options;
        return new InMemoryDbContext(options);
    }

    private SpeakerRepository GetRepository(InMemoryDbContext context)
    {
        var loggerMock = new Mock<ILogger<SpeakerRepository>>();
        return new SpeakerRepository(context, loggerMock.Object);
    }

    private Speaker GetSampleModel(int id = 1) => new Speaker
    {
        Id = id,
        FirstName = "John",
        LastName = "Doe",
        Sat = true,
        Sun = false,
        Favorite = false,
        Bio = "Bio",
        Company = "Company",
        TwitterHandle = "@john",
        UserBioShort = "Short bio",
        ImageUrl = "http://img",
        Email = "john@example.com",
        Photo = "photo"
    };

    [Fact]
    public async Task GetAllAsync_ReturnsEmpty_WhenNoSpeakers()
    {
        var dbName = Guid.NewGuid().ToString();
        using var context = GetDbContext(dbName);
        var repo = GetRepository(context);

        var result = await repo.GetAllAsync();

        Assert.NotNull(result);
        Assert.Empty(result);
    }

    [Fact]
    public async Task GetAsync_ReturnsNull_WhenIdIsNegative()
    {
        var dbName = Guid.NewGuid().ToString();
        using var context = GetDbContext(dbName);
        var repo = GetRepository(context);

        var result = await repo.GetAsync(-1);

        Assert.Null(result);
    }

    [Fact]
    public async Task GetAsync_ReturnsNull_WhenIdIsZero()
    {
        var dbName = Guid.NewGuid().ToString();
        using var context = GetDbContext(dbName);
        var repo = GetRepository(context);

        var result = await repo.GetAsync(0);

        Assert.Null(result);
    }

    [Fact]
    public async Task AddAsync_ThrowsArgumentException_WhenSpeakerIsNull()
    {
        var dbName = Guid.NewGuid().ToString();
        using var context = GetDbContext(dbName);
        var repo = GetRepository(context);

        await Assert.ThrowsAsync<ArgumentException>(() => repo.AddAsync(null));
    }

    [Fact]
    public async Task AddAsync_AllowsSpeakerWithMinimalData()
    {
        var dbName = Guid.NewGuid().ToString();
        using var context = GetDbContext(dbName);
        var repo = GetRepository(context);

        var model = new Speaker { Id = 2 };

        var result = await repo.AddAsync(model);

        Assert.NotNull(result);
        Assert.Equal(2, result.Id);
    }

    [Fact]
    public async Task AddAsync_AllowsSpeakerWithNullAndEmptyFields()
    {
        var dbName = Guid.NewGuid().ToString();
        using var context = GetDbContext(dbName);
        var repo = GetRepository(context);

        var model = new Speaker
        {
            Id = 3,
            FirstName = null,
            LastName = "",
            Bio = null,
            Company = "",
            TwitterHandle = null,
            UserBioShort = "",
            ImageUrl = null,
            Email = "",
            Photo = null
        };

        var result = await repo.AddAsync(model);

        Assert.NotNull(result);
        Assert.Equal(3, result.Id);
        Assert.Null(result.FirstName);
        Assert.Equal("", result.LastName);
    }

    [Fact]
    public async Task UpdateAsync_ThrowsArgumentException_WhenSpeakerNotFound()
    {
        var dbName = Guid.NewGuid().ToString();
        using var context = GetDbContext(dbName);
        var repo = GetRepository(context);

        var model = GetSampleModel(99);

        await Assert.ThrowsAsync<ArgumentException>(() => repo.UpdateAsync(model));
    }

    [Fact]
    public async Task UpdateAsync_UpdatesSpeaker_WithNullFields()
    {
        var dbName = Guid.NewGuid().ToString();
        using var context = GetDbContext(dbName);
        var entity = new SpeakerEntity { Id = 4, FirstName = "A", LastName = "B" };
        context.Speakers.Add(entity);
        context.SaveChanges();

        var repo = GetRepository(context);

        var updated = new Speaker
        {
            Id = 4,
            FirstName = null,
            LastName = null,
            Sat = false,
            Sun = false,
            Favorite = false,
            Bio = null,
            Company = null,
            TwitterHandle = null,
            UserBioShort = null,
            ImageUrl = null,
            Email = null,
            Photo = null
        };

        var result = await repo.UpdateAsync(updated);

        Assert.NotNull(result);
        Assert.Null(result.FirstName);
        Assert.Null(result.LastName);
    }

    [Fact]
    public async Task DeleteAsync_ThrowsArgumentException_WhenSpeakerNotFound()
    {
        var dbName = Guid.NewGuid().ToString();
        using var context = GetDbContext(dbName);
        var repo = GetRepository(context);

        await Assert.ThrowsAsync<ArgumentException>(() => repo.DeleteAsync(999));
    }

    [Fact]
    public async Task DeleteAsync_DeletesSpeaker_WithZeroId()
    {
        var dbName = Guid.NewGuid().ToString();
        using var context = GetDbContext(dbName);
        context.Speakers.Add(new SpeakerEntity { Id = 11 });
        context.SaveChanges();

        var repo = GetRepository(context);

        var result = await repo.DeleteAsync(11);

        Assert.True(result);
        Assert.Empty(context.Speakers);
    }
}